"""Water domain events emitted by the soil water model.

The events defined here have water-only scope, enabling other modules
(e.g., nutrients) to subscribe without creating tight coupling.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple


@dataclass(frozen=True)
class WaterInfiltrated:
    """Infiltration amounts added to specific layers.

    Attributes:
        layer_indices: Zero-based indices of layers receiving water.
        amounts_mm: Water amounts added to each layer (mm).
    """

    layer_indices: Tuple[int, ...]
    amounts_mm: Tuple[float, ...]


@dataclass(frozen=True)
class WaterDrained:
    """Drainage between adjacent layers during cascade.

    Attributes:
        from_layer: Source layer index.
        to_layer: Destination layer index.
        amount_mm: Water amount moved (mm).
    """

    from_layer: int
    to_layer: int
    amount_mm: float


@dataclass(frozen=True)
class RunoffGenerated:
    """Surface runoff generated by SCS CN method.

    Attributes:
        amount_mm: Runoff depth (mm).
        curve_number: SCS curve number used.
    """

    amount_mm: float
    curve_number: int


@dataclass(frozen=True)
class EvaporationTaken:
    """Actual evaporation removed from the top layer.

    Attributes:
        amount_mm: Evaporation depth taken (mm).
    """

    amount_mm: float
